version: '3.8'

services:
  backend:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lyriclens_backend
    command: sh -c "python3 manage.py migrate --noinput &&  python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ../lyriclens-server:/app
    env_file:
      - ../.env
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - redis
  
  redis:
    image: redis:7-alpine
    container_name: lyriclens_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  data:
  redis_data: